[package]
name = "hu"
version = "0.1.0"
edition = "2021"
description = "Dev workflow CLI"
license = "MIT"

[[bin]]
name = "hu"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "color", "wrap_help"] }
anyhow = "1.0"
directories = "5"

[dev-dependencies]

[profile.release]
lto = true
strip = true
codegen-units = 1
