name: Test

# Temporarily disabled
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: extractions/setup-just@v2
      - run: just ci-fmt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Auto-format code with rustfmt"
          file_pattern: "*.rs"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: format
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git pull origin ${{ github.head_ref || github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: extractions/setup-just@v2
      - run: just ci-lint-fix
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix: Auto-fix clippy warnings"
          file_pattern: "*.rs"
      - run: just ci-lint-check

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: [format, lint]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - run: git pull origin ${{ github.head_ref || github.ref_name }}
        shell: bash
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v2
      - run: just ci-test
