name: types

on:
  workflow_run:
    workflows: [format]
    types: [completed]
    branches: [master]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  types:
    name: types
    runs-on: ubuntu-latest
    environment: types
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Type check
        run: cargo check --all-targets
